### ISSUE TITLE
Error on Win

### ISSUE THREAD

**Issue by cannap** [optilude/meteor-react-example#2]
Hi, i Cloned the Repo

System:
Windows 8.1
Meteor: latest

Meteor starting Downloading jsx and after the Download i got this error
```javascript
C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
TypeError: Cannot call method 'replace' of null
    at convert (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:49:15)
    at convertBySchema (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:18:12)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:42:18
    at Function._.each._.forEach (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at convertBySchema (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:40:5)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:32:14
    at Array.map (native)
    at Function._.map._.collect (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:98:56)
    at convertBySchema (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:31:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:42:18
    at Function._.each._.forEach (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at convertBySchema (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:40:5)
    at Object.exports.convertJSImage (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:88:10)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:120:44
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Object.exports._extractAndConvert (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:111:7)
    at [object Object]._.extend._downloadBuildToTempDir (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:295:20)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:462:37
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:460:11
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at Object.download (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:419:20)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:553:22
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:550:20)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:668:25
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:667:20
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\catalog.js:100:5
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:666:13)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:238:35
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:221:10)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:520:29
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at bundleApp (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:519:31)
    at [object Object]._.extend._runOnce (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:591:35)
    at [object Object]._.extend._fiber (C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:821:28)
    at C:\Users\marko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:402:12

```

**Comment by JustinNicholls** [comment]
Do not clone it since it could contain different configurations depending on the os. I got it working by creating the packages normally then copying and pasting the files into the package

**Comment by JustinNicholls** [comment]
nvm i still can not get it working
